#include <Windows.h>
#include <stdlib.h>
#include "LogInfo.h"
#include "inih\ini.h"
#pragma once

#define APP_CONFIG_KEY			"Software\\MCEDP\\Applications\\"
#define MAIN_CONFIG_KEY			"Software\\MCEDP"
#define MATCH_CONF(s, n)		stricmp(s, n) == 0


typedef struct _MCEDPREGCONFIG
{
	BOOL PROCESS_HOOKED;						// IMPLEMENTE
	BOOL SKIP_HBP_ERROR;						// IMPLEMENTE
	DWORD INIT_DELAY;							// IMPLEMENTE
	DWORD APP_ID;								// IMPLEMENTE 
	CHAR APP_PATH[MAX_PATH];					// IMPLEMENTE
	CHAR LOG_PATH[MAX_PATH];					// IMPLEMENTE
    CHAR DBG_LOG_PATH[MAX_PATH];				// IMPLEMENTE
	CHAR MCEDP_MODULE_PATH[MAX_PATH];			// IMPLEMENTE
	CHAR APP_PATH_HASH[MAX_PATH];   			// IMPLEMENTE

	struct {
		CHAR ETAF_MODULE[MAX_MODULE_NAME32];	// IMPLEMENTE
		BOOL ALLOW_MALWARE_DWONLOAD;			// IMPLEMENTE
		BOOL KILL_SHELLCODE;					// IMPLEMENTE
		BOOL DUMP_SHELLCODE;					// IMPLEMENTE
		BOOL ETA_VALIDATION;					// IMPLEMENTE
		BOOL SYSCALL_VALIDATION;
		BOOL ANALYSIS_SHELLCODE;				// IMPLEMENTE
	} SHELLCODE;

	struct {
		BOOL DETECT_ROP;						// IMPLEMENTE
		BOOL KILL_ROP;							// IMPLEMENTE
		BOOL CALL_VALIDATION;
		BOOL FORWARD_EXECUTION;
		DWORD FE_FAR;
		BOOL STACK_MONITOR;						// IMPLEMENTE
		BOOL PIVOTE_DETECTION;
		DWORD PIVOTE_TRESHOLD;
		DWORD PIVOTE_INST_TRESHOLD;				
		BOOL DUMP_ROP;							// IMPLEMENTE
		BOOL MAX_ROP_INST;						// IMPLEMENTE
		BOOL MAX_ROP_MEM;						// IMPLEMENTE
		DWORD ROP_MEM_FAR;						// IMPLEMENTE
	} ROP;

	struct {
		BOOL TEXT_RWX;
		BOOL STACK_RWX;							// IMPLEMENTE
		BOOL TEXT_RANDOMIZATION;
	} MEM;

	struct {
		PCHAR HEAP_SPRAY_ADDRESS;				// IMPLEMENTE
		BOOL HEAP_SPRAY;						// IMPLEMENTE
		BOOL NULL_PAGE;							// IMPLEMENTE
		BOOL SEHOP;
		BOOL PERMANENT_DEP;						// IMPLEMENTE
		BOOL ALLOW_MALWARE_EXEC;				// IMPLEMENTE
	} GENERAL;

} MCEDPREGCONFIG, *PMCEDPREGCONFIG;

extern MCEDPREGCONFIG MCEDP_REGCONFIG;
extern HMODULE hGlobalDllHandle;

STATUS
ParsRegConfig(
	OUT PMCEDPREGCONFIG pMcedpRegConfig,
	IN PCHAR szAppPathHash,
	IN DWORD Size
	);
